name: Bored Lines of Code
on: [push]
jobs:
  loc:
    runs-on: ubuntu-latest
    name: loc
    steps:
      - uses: actions/checkout@v1
      - name: install tokei
        run: "cargo install --git https://github.com/XAMPPRocky/tokei.git tokei"
        
      - name: cloning borehtml
        run: "git clone https://github.com/PiSaucer/boredhtml.git"
      - run: "cd boredhtml"
        
      - name: tokei 
        run: tokei --output json > data.json
      - run: cat data.json
      
      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: main # Pushes the updates to the master branch.
          folder: / # The location of the data.json file saved by the Fetch API Data action.
          target-folder: bored/loc # Saves the data into the 'data' directory on the master branch
            
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'total lines'
          status: 'function'
          color: 'yellow'
          path: ./bored/loc.svg

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: ./bored/loc.svg
          if-no-files-found: error

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Commit badge
        env:
          BADGE: ./bored/loc.svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Bored Update LOC Badge"
          
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
