name: School Daily Badge
on:
  schedule: [{cron: "0 * * * *"}]
jobs:
  create-badge:
      runs-on: ubuntu-latest
      name: Create Badge
      steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v2
          with:
            persist-credentials: false
            
        - name: Fetch API Data 📦
          run: curl https://data.jsdelivr.com/v1/package/gh/Bored-Entertainment/Schoolgrounds/stats/version/day > data.json
          
        - name: Read Data From Json 📚
          id: read-data
          uses: notiz-dev/github-action-json-property@release
          with: 
            path: 'data.json'
            prop_path: 'total'

        - name: Sigin to git
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"

        - name: Remove old Badge
          run: |
            git rm school/day.svg
            git commit -m "remove school/day.svg"

        - name: Generate the badge SVG image
          uses: emibcn/badge-action@v1
          id: badge
          with:
            label: 'cdn.schgnd.ml'
            status: ${{ steps.read-data.outputs.prop }} hits/today
            color: 'orange'
            path: ./school/day.svg

        - name: Upload badge as artifact
          uses: actions/upload-artifact@v2
          with:
            name: badge
            path: ./school/day.svg
            if-no-files-found: error

        - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch
        - name: Commit badge
          env:
            BADGE: ./school/day.svg
          run: |
            git add "${BADGE}"
            git commit -m "School Update Daily Badge"
        - name: Push badge commit
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ steps.extract_branch.outputs.branch }}
